require:
  - standard

plugins:
  - standard-performance
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

Layout/ArrayAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key
  EnforcedLastArgumentHashStyle: always_inspect

Layout/LineLength:
  Max: 140

Layout/ParameterAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: ~

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false

Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias_method

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
